blank_issues_enabled: false
contact_links:
  - name: 💬 Perguntas gerais / Suporte
    url: https://github.com/coldpay-company/discussions
    about: Use Discussions para dúvidas e suporte antes de abrir uma issue.
